<select id="language" onchange="changelang(this.value)">
<option value="en">&mdash;</option>
<option value="ar">‫العربية‬ (ar)</option>
<option value="pt_BR">Português (Brazil) (pt_BR)</option>
<option value="bg">български (bg)</option>
<option value="ca">Català (ca)</option>
<option value="hr">Hrvatski (hr)</option>
<option value="cs">česky (cs)</option>
<option value="nl">Nederlands (nl)</option>
<option value="fi">Suomen (fi)</option>
<option value="fr">français (fr)</option>
<option value="de">Deutsch (de)</option>
<option value="el">Ελληνικά (el)</option>
<option value="en">English (en)</option>
<option value="hrx">Hunns-rikk (hrx)</option>
<option value="it">Italiano (it)</option>
<option value="ja">日本語 (ja)</option>
<option value="pl">Polski (pl)</option>
<option value="pt">Português (pt)</option>
<option value="ru">русский (ru)</option>
<option value="es">español (es)</option>
</select>
