<a href="http://www.stellarium.org/zh/">正體中文</a>
 - 
<a href="http://www.stellarium.org/ca/">Català</a>
 - 
<a href="http://www.stellarium.org/cs/">Česky</a>
 - 
<a href="http://www.stellarium.org/de/">Deutsch</a>
 - 
<a href="http://www.stellarium.org/el/">Ελληνικά</a>
 - 
<a href="http://www.stellarium.org">English</a>
 - 
<a href="http://www.stellarium.org/es/">Español</a>
 - 
<a href="http://www.stellarium.org/eo/">Esperanto</a>
 - 
<a href="http://www.stellarium.org/fr/">Français</a>
 - 
<a href="http://www.stellarium.org/ko/">한국어</a>
 - 
<a href="http://www.stellarium.org/sq/">Shqip</a>
 -  
<a href="http://www.stellarium.org/hr/">Hrvatski</a>
 - 
<a href="http://www.stellarium.org/it/">Italiano</a>
 - 
<a href="http://www.stellarium.org/ka/">ქართული</a>
 - 
<a href="http://www.stellarium.org/ru/">Русский</a>
 - 
<a href="http://www.stellarium.org/sw/">Kiswahili</a>
 - 
<a href="http://www.stellarium.org/hu/">Magyar</a>
 - 
<a href="http://www.stellarium.org/nl/">Nederlands</a>
 - 
<a href="http://www.stellarium.org/pl/">Polski</a>
 - 
<a href="http://www.stellarium.org/pt/">Português</a>
 -
<a href="http://www.stellarium.org/fi/">Suomi</a>
 - 
<a href="http://www.stellarium.org/ja/">日本語</a>
